### PR TITLE
arrow builder: speed up bitsetting for large length

### PR DESCRIPTION
**Pull request by atumanov**

### CODE REVIEW

**Comment by wesm** [comment]
Can you submit a pull request to Arrow? Thanks

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-607

**Comment by robertnishihara** [comment]
I think we just copied this change from the upstream arrow (from this commit https://github.com/apache/arrow/commit/ad0157547a4f5e6e51fa2f712c2ed9477489a20c).

**Comment by robertnishihara** [comment]
We're planning on rebasing on the Arrow master soon.

**Comment by atumanov** [comment]
yes, this was an interim solution until we update arrow. I cherry picked the code and just changed the types to fit our current code base.

**Pull request merged**
